console.log("Hello World!!!") 
console.log("Welcome to the Javascript Tutorial...")


console.log("Javascript is a dynamicaaly type language...")
fullName = 25
console.log("fullName : ", fullName)

// console.log("It means that the data type of a variable is determined at runtime...")
// console.log("It is a case sensitive language...")
// console.log("It is a first class function...")
// console.log("It supports object oriented programming...")
// console.log("It supports functional programming...")    
// console.log("It supports asynchronous programming...")
// console.log("It supports event driven programming...")
// console.log("It supports prototype based inheritance...")
// console.log("It supports closures...")
// console.log("It supports callbacks...")
// console.log("It supports promises...")
// console.log("It supports async/await...")
// console.log("It supports modules...")
// console.log("It supports classes...")
// console.log("It supports interfaces...")
// console.log("It supports enums...")
// console.log("It supports type annotations...")
// console.log("It supports type inference...")
// console.log("It supports type checking...")
// console.log("It supports type casting...")
// console.log("It supports type coercion...")
// console.log("It supports type conversion...")
// console.log("It supports type widening...")
// console.log("It supports type narrowing...")
// console.log("It supports type guards...")
// console.log("It supports type predicates...")
